### ISSUE TITLE
Travis Build fails wanting PKG_CONFIG_ALLOW_CROSS=1

### ISSUE THREAD

**Issue by mmstick** [japaric/trust#79]
Having an odd issue where Travis fails to build with the error:

```
Cross compilation detected. Use PKG_CONFIG_ALLOW_CROSS=1 to override
```

Even though I have it specified as a global environment variable in the file:

```yaml
env:
  global:
    - CRATE_NAME=tv-renamer
    - GTK=3.18
    - PKG_CONFIG_ALLOW_CROSS=1
    - LD_LIBRARY_PATH="$HOME/local/lib/"
    - PKG_CONFIG_PATH="$HOME/local/lib/pkgconfig"
```

Any ideas on how to get this working?
